import React, { useEffect, useRef, useState } from 'react';
import { registerPlugin } from '@capacitor/core';
import { Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';

type Device = { name: string; host: string; port: number; endpoint: string };
type DiscoveryPlugin = { startDiscovery(): Promise<void>; stopDiscovery(): Promise<void>; addListener(event: 'deviceFound', listener: (device: Device) => void): Promise<{ remove: () => Promise<void> }> };
const Discovery = registerPlugin<DiscoveryPlugin>('ProjectedDiscovery');

export default function App() {
  const videoRef = useRef<HTMLVideoElement | null>(null), canvasRef = useRef<HTMLCanvasElement | null>(null), streamRef = useRef<MediaStream | null>(null), socketRef = useRef<WebSocket | null>(null), timerRef = useRef<number | null>(null);
  const [devices, setDevices] = useState<Device[]>([]), [selected, setSelected] = useState<Device | null>(null), [status, setStatus] = useState('idle'), [message, setMessage] = useState('Tap scan to find a desktop receiver nearby.'), [sent, setSent] = useState(0);

  useEffect(() => { let listener: { remove: () => Promise<void> } | undefined; Discovery.addListener('deviceFound', device => setDevices(items => items.some(item => item.host === device.host && item.port === device.port) ? items : [...items, device])).then(handle => listener = handle).catch(() => setMessage('Browser preview ready. Device radar activates in the Android app.')); return () => { listener?.remove(); stop(); Discovery.stopDiscovery().catch(() => undefined); }; }, []);
  async function scan() { setDevices([]); setSelected(null); setStatus('scanning'); setMessage('Scanning the local network for Projected AI desktops…'); try { await Discovery.startDiscovery(); } catch { setStatus('idle'); setMessage('Open the Android build to use automatic local discovery.'); } }
  async function startCamera() { try { setStatus('starting'); const media = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment', width: { ideal: 1280 }, height: { ideal: 720 } }, audio: false }); streamRef.current = media; if (videoRef.current) { videoRef.current.srcObject = media; await videoRef.current.play(); } setStatus('ready'); setMessage('Camera ready. Select a discovered desktop to connect.'); } catch (error) { setStatus('error'); setMessage(error instanceof Error ? error.message : 'Camera permission failed.'); } }
  function connect(device: Device) { if (!streamRef.current) { setMessage('Start the camera first.'); return; } const socket = new WebSocket(device.endpoint); socketRef.current = socket; setSelected(device); socket.onopen = () => { setStatus('streaming'); setMessage(`Connected to ${device.name}. Streaming locally.`); startSending(); }; socket.onclose = () => { stopSending(); setStatus('ready'); setMessage('Desktop connection closed.'); }; socket.onerror = () => { setStatus('error'); setMessage('Desktop was found but the frame receiver is unavailable.'); }; }
  function startSending() { stopSending(); timerRef.current = window.setInterval(() => { const video = videoRef.current, canvas = canvasRef.current, socket = socketRef.current; if (!video || !canvas || !socket || socket.readyState !== WebSocket.OPEN || !video.videoWidth) return; canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d')?.drawImage(video, 0, 0); canvas.toBlob(blob => { if (blob && socket.readyState === WebSocket.OPEN) { socket.send(blob); setSent(value => value + 1); } }, 'image/jpeg', .72); }, 200); }
  function stopSending() { if (timerRef.current !== null) { clearInterval(timerRef.current); timerRef.current = null; } }
  function stop() { stopSending(); socketRef.current?.close(); streamRef.current?.getTracks().forEach(track => track.stop()); streamRef.current = null; }
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Text style={styles.eyebrow}>PROJECTED AI INTERFACE</Text><Text style={styles.title}>Connect Camera</Text><Text style={styles.subtitle}>Automatic local-device discovery</Text></View><View style={styles.preview}><video ref={videoRef} playsInline muted style={{ width: '100%', height: '100%', objectFit: 'cover' }} /><canvas ref={canvasRef} style={{ display: 'none' }} /><View style={styles.badge}><Text style={styles.badgeText}>{status === 'scanning' ? 'RADAR ACTIVE' : status.toUpperCase()}</Text></View><View style={styles.radar}><View style={styles.radarLine} /><View style={styles.radarDot} /></View></View><View style={styles.actions}><Pressable onPress={scan} style={styles.primary}><Text style={styles.primaryText}>Scan for desktop</Text></Pressable><Pressable onPress={startCamera} style={styles.secondary}><Text style={styles.secondaryText}>Start camera</Text></Pressable></View><Text style={styles.message}>{message}</Text><View style={styles.devices}>{devices.length === 0 ? <Text style={styles.empty}>No nearby desktops yet. Make sure the desktop receiver is running on the same Wi-Fi network.</Text> : devices.map(device => <Pressable key={`${device.host}:${device.port}`} onPress={() => connect(device)} style={[styles.device, selected?.host === device.host && styles.deviceSelected]}><View style={styles.deviceIcon}><Text style={styles.iconText}>▣</Text></View><View><Text style={styles.deviceName}>{device.name}</Text><Text style={styles.deviceMeta}>{device.host}  •  Ready</Text></View><Text style={styles.chevron}>›</Text></Pressable>)}</View><Text style={styles.stats}>Frames sent: {sent}  •  Local network only</Text></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#0b1220', padding: 20 }, header: { paddingTop: 12, paddingBottom: 18 }, eyebrow: { color: '#55d6be', fontSize: 12, fontWeight: '700', letterSpacing: 1.5 }, title: { color: '#f5f7fb', fontSize: 32, fontWeight: '800', marginTop: 6 }, subtitle: { color: '#8ea6c7', fontSize: 14, marginTop: 4 }, preview: { height: 270, backgroundColor: '#162238', borderRadius: 22, overflow: 'hidden', borderWidth: 1, borderColor: '#2b3d59', position: 'relative' }, badge: { position: 'absolute', top: 14, left: 14, backgroundColor: '#0b1220cc', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 7 }, badgeText: { color: '#55d6be', fontSize: 11, fontWeight: '800' }, radar: { position: 'absolute', right: 24, bottom: 24, width: 64, height: 64, borderRadius: 64, borderWidth: 1, borderColor: '#55d6be66' }, radarLine: { position: 'absolute', left: 31, top: 5, width: 1, height: 27, backgroundColor: '#55d6be' }, radarDot: { position: 'absolute', left: 29, top: 29, width: 5, height: 5, borderRadius: 5, backgroundColor: '#55d6be' }, actions: { flexDirection: 'row', gap: 10, marginTop: 18 }, primary: { backgroundColor: '#4d83d1', borderRadius: 12, paddingVertical: 14, paddingHorizontal: 18 }, primaryText: { color: 'white', fontWeight: '800' }, secondary: { borderColor: '#52769d', borderWidth: 1, borderRadius: 12, paddingVertical: 14, paddingHorizontal: 16 }, secondaryText: { color: '#c6d5e8', fontWeight: '700' }, message: { color: '#55d6be', marginTop: 18, minHeight: 38 }, devices: { gap: 10 }, empty: { color: '#71809a', lineHeight: 21 }, device: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#162238', borderRadius: 14, padding: 14, borderWidth: 1, borderColor: '#2b3d59' }, deviceSelected: { borderColor: '#55d6be' }, deviceIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: '#28527d', alignItems: 'center', justifyContent: 'center', marginRight: 12 }, iconText: { color: '#55d6be', fontSize: 20 }, deviceName: { color: '#f5f7fb', fontWeight: '800' }, deviceMeta: { color: '#8ea6c7', fontSize: 12, marginTop: 3 }, chevron: { marginLeft: 'auto', color: '#55d6be', fontSize: 28 }, stats: { color: '#71809a', fontSize: 12, marginTop: 16 } });
